version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: procurement-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      # Add other environment variables here if needed
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:3000
    restart: always
